<?php

namespace Origem\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrigemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigemRepository extends EntityRepository
{
}
