<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li>
            <a href="<?php
            echo $this->url(
                'gerador/default',
                array(
                    'controller' => 'gerador',
                    'action' => 'criarController'
                )
            );
            ?>">Controller Generator</a>
        </li>
        <li>
            <a href="<?php
            echo $this->url(
                'gerador/default',
                array(
                    'controller' => 'gerador',
                    'action' => 'criarForm'
                )
            );
            ?>">Form Generator</a>
        </li>
        <li class="active">
            <a href="<?php
            echo $this->url(
                'gerador/default',
                array(
                    'controller' => 'gerador',
                    'action' => 'criarFilter'
                )
            );
            ?>">Filter Generator</a>
        </li>
    </ul>
</div>

<div class="col-lg-9">
    <div>
        <h2>Form Generator!</h2>
    </div>
    <br/><br/>

    <p>Insira os parametros para a gerar o novo Form</p>

    <?php

    $form = $this->form;

    $this->formElementErrors()
        ->setMessageOpenFormat(
            '<p class="text-danger">'
        )
        ->setMessageCloseString('</p>')
        ->render($form);

    $form->prepare();

    echo $this->form()->openTag($form);

    ?>
    <div class="col-lg-12">
        <?php

        foreach ($form as $element) { ?>
            <div class="form-group">
                <?php
                if ($element->getAttribute('type') != 'submit') {
                    echo('<label for="' . $element->getAttribute('id') . '">' . $element->getLabel() . '</label>');
                    echo($this->formElement($element));
                } else {
                    echo($this->formInput($element));
                }
                echo($this->formElementErrors($element));
                ?>
            </div>
            <?php
        }
        ?>
    </div>
    <?php

    echo $this->form()->closeTag();
    ?>
</div>