<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li>
            <a href="<?php
            echo $this->url(
                'gerador/default',
                array(
                    'controller' => 'gerador',
                    'action' => 'criarController'
                )
            );
            ?>">Controller Generator</a>
        </li>
        <li>
            <a href="<?php
            echo $this->url(
                'gerador/default',
                array(
                    'controller' => 'gerador',
                    'action' => 'criarForm'
                )
            );
            ?>">Form Generator</a>
        </li>
    </ul>
</div>

<div class="col-lg-9">
    <div>
        <h2>Welcome to Zend Framework Code Generator!</h2>
    </div>
    <br/><br/>
    <p>
        You may use the following generators to quickly build up your ZF2 application:

    <ul>
        <li>
            <a
                href="<?php echo $this->url(
                    'gerador/default',
                    array('controller' => 'gerador', 'action' => 'criarController')
                ); ?>">
                Controller Generator
            </a>
        </li>
        <li>
            <a
                href="<?php echo $this->url(
                    'gerador/default',
                    array('controller' => 'gerador', 'action' => 'criarForm')
                ); ?>">
                Form Generator
            </a>
        </li>
    </ul>
    <br/>
    Other code generators will be available in the future:<br/>
    <br/>
    <ul>
        <li>Controller Generator</li>
        <li>Form Generator</li>
        <li>Model Generator</li>
    </ul>
    </p>
</div>