<h2>Cadastrar Post</h2>

<?php
    /**
     * @var $form \Zend\Form\Form
     */
    $form = $this->form;

    $this->formElementErrors()
        ->setMessageOpenFormat ('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
        ->setMessageCloseString ('</div>')
        ->render ($form);

    $form->setAttribute('action', $this->url('origem/default', array('controller' => 'origem', 'action' => 'inserir')));

    $form->prepare();

    echo $this->form()->openTag($form);

    echo $this->formCollection($form);

    echo $this->form()->closeTag();
?>

<style type="text/css">
    input, textarea, label, select {
      display: block;
    }
</style>

