<h2>Cadastrar Categoria</h2>

<?php
    /**
     * @var $form \Zend\Form\Form
     */
    $form = $this->form;

    $this->formElementErrors()
        ->setMessageOpenFormat ('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
        ->setMessageCloseString ('</div>')
        ->render ($form);

    $form->setAttribute('action', $this->url('categoria/default', array('controller' => 'categoria', 'action' => 'inserir')));

    $form->prepare();

    echo $this->form()->openTag($form);

?>
<div class="col-lg-12">
    <?php

    foreach ($form as $element) { ?>
        <div class="form-group">
            <?php
            if ($element->getAttribute('type') != 'submit') {
                echo ('<label for="' . $element->getAttribute('id') .'">'. $element->getLabel() . '</label>');
                echo($this->formElement($element));
            } else {
                echo($this->formInput($element));
            }
            echo($this->formElementErrors($element));
            ?>
        </div>
        <?php
    }
    ?>
</div>
<?php

    echo $this->form()->closeTag();
?>

