<?php

namespace Lancamentos\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LancamentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LancamentosRepository extends EntityRepository
{
}
