<h2>Editar Lançamento</h2>

<?php
    /**
     * @var $form \Zend\Form\Form
     */
    $form = $this->form;

    $this->formElementErrors()
        ->setMessageOpenFormat ('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
        ->setMessageCloseString ('</div>')
        ->render ($form);

    $form->setAttribute('action', $this->url('lancamentos/default', array('controller' => 'lancamentos', 'action' => 'editar', 'id' => $this->id)));

    $form->prepare();

    echo $this->form()->openTag($form);

    foreach ($form as $element) {
        echo($element->getOpentag());
        if ($element->getAttribute('type') != 'submit') {
            echo($this->formLabel($element));
        }
        echo($this->formInput($element));
        echo($this->formElementErrors($element));
        echo($element->getClosetag());
    }

    echo $this->form()->closeTag();
?>

<style type="text/css">
    input, textarea, label, select {
        display: block;
    }
</style>