<a class="btn btn-success" href="<?php echo $this->url('lancamentos/default', array('controller' => 'lancamentos', 'action' => 'inserir')); ?>">Cadastar</a>
<hr>

<h2>Todos os Lançamentos</h2>
<form id="form-grid" action="" method="post">
    <table class="table table-striped table-hover table-condensed">
        <thead>
        <tr>
            <th>Categoria</th>
            <th>Origem</th>
            <th>Operação</th>
            <th>Valor Inicial</th>
            <th>Valor Final</th>
            <th>Tipo</th>
            <th>AÇÃO</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach( $this->data as $entity): ?>
            <tr>
                <td><?php echo $entity->getCategoria()->getName(); ?></td>
                <td><?php echo $entity->getOrigem()->getName(); ?></td>
                <td><?php echo $entity->getOperacao()->getName(); ?></td>
                <td><?php echo $entity->getValorInicial(); ?></td>
                <td><?php echo $entity->getValorFinal(); ?></td>
                <td>
                    <i class="<?php echo $entity->getTipo()->getIcon(); ?>" aria-hidden="true"></i>
                </td>
                <td>
                    <a class="btn btn-sm btn-success" href="<?php echo $this->url('lancamentos/default', array('controller' => 'lancamentos', 'action' => 'editar', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-pencil"></i> </a>
                    <a class="btn btn-sm btn-danger" href="<?php echo $this->url('lancamentos/default', array('controller' => 'lancamentos', 'action' => 'excluir', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-remove-sign"></i> </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>
