<?php
echo $this->doctype();
$strPageNamespace = $this->viewModel()->getCurrent()->getChildren()[0]->getTemplate();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Financeiro'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/css/style.css'); ?>
    <!-- Latest compiled and minified CSS -->
    <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
    <!-- Latest compiled and minified JavaScript -->
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><?php echo 'Financeiro' ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <!-- init li::categoria -->
                <li class="<?php if ($strPageNamespace == 'categoria/index/index') {echo('active');} ?>">
                    <a href="<?php echo $this->url('categoria', array('action' => 'default')); ?>">
                        Categoria
                    </a>
                </li>
                <!-- end li::categoria -->
                <!-- init li::operacoes -->
                <li class="<?php if ($strPageNamespace == 'operacoes/index/index') {echo('active');} ?>">
                    <a href="<?php echo $this->url('operacoes', array('action' => 'default')); ?>">
                        Operações
                    </a>
                </li>
                <!-- end li::operacoes -->
                <!-- init li::origem -->
                <li class="<?php if ($strPageNamespace == 'origem/index/index') {echo('active');} ?>">
                    <a href="<?php echo $this->url('origem', array('action' => 'default')); ?>">
                        Origem
                    </a>
                </li>
                <!-- end li::origem -->
                <!-- init li::tipo -->
                <li class="<?php if ($strPageNamespace == 'tipo/index/index') {echo('active');} ?>">
                    <a href="<?php echo $this->url('tipo', array('action' => 'default')); ?>">
                        Tipo
                    </a>
                </li>
                <!-- end li::tipo -->
                <!-- init li::prioridade -->
                <li class="dropdown" class="<?php if ($strPageNamespace == 'prioridade/index/index') {echo('active');} ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Prioridade <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('prioridade', array('action' => 'default')); ?>">Listar Todos</a></li>
                        <li>
                            <a href="<?php echo $this->url('prioridade/default', array('controller' => 'prioridade', 'action' => 'inserir')); ?>">Adicionar</a>
                        </li>
                    </ul>
                </li>
                <!-- end li::prioridade -->
                <!-- init li::lancamentos -->
                <li class="dropdown" class="<?php if ($strPageNamespace == 'lancamentos/index/index') {echo('active');} ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lançamentos <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('lancamentos', array('action' => 'default')); ?>">Listar Todos</a></li>
                        <li>
                            <a href="<?php echo $this->url('lancamentos/default', array('controller' => 'lancamentos', 'action' => 'inserir')); ?>">Adicionar</a>
                        </li>
                    </ul>
                </li>
                <!-- end li::lancamentos -->
                <!-- init li::gerador -->
                <li class="dropdown" class="<?php if ($strPageNamespace == 'gerador/index/index') {echo('active');} ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gerador <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('gerador', array('action' => 'index')); ?>">Index</a></li>
                        <li>
                            <a href="<?php echo $this->url('gerador/default', array('controller' => 'gerador', 'action' => 'criarController')); ?>">Criar Controller</a>
                        </li>
                    </ul>
                </li>
                <!-- end li::gerador -->
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php
    echo $this->flashMessenger()->render("error", array('alert', 'alert-danger'));
    echo $this->flashMessenger()->render("success", array('alert', 'alert-success'));
    echo $this->flashMessenger()->render("warning", array('alert', 'alert-warning'));
    echo $this->content;
    ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
