<a class="btn btn-success"
   href="<?php echo $this->url('prioridade/default', array('controller' => 'prioridade', 'action' => 'inserir')); ?>">Cadastar</a>
<hr>

<h1>Todas as prioridades</h1>

<table class="table table-bordered table-striped table-hover table-condensed">
    <thead>
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Icone</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    <?php if ($this->data): ?>
        <?php foreach ($this->data as $entity): ?>
            <tr>
                <td><?php echo $entity->getId(); ?></td>
                <td><?php echo $entity->getName(); ?></td>
                <td>
                    <i class="<?php echo $entity->getIcon(); ?>" aria-hidden="true"></i>
                </td>
                <td>
                    <a class="btn btn-success" href="<?php echo $this->url('prioridade/default',
                        array('controller' => 'prioridade', 'action' => 'editar', 'id' => $entity->getId())); ?>"><i
                            class="glyphicon glyphicon-pencil"></i> </a>
                    <a class="btn btn-danger" href="<?php echo $this->url('prioridade/default',
                        array('controller' => 'prioridade', 'action' => 'excluir', 'id' => $entity->getId())); ?>"><i
                            class="glyphicon glyphicon-remove-sign"></i> </a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <p>Nenhum registro encontrado!</p>
    <?php endif; ?>


    </tbody>
</table>