<?php

namespace Prioridade\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrioridadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioridadeRepository extends EntityRepository
{
}
