<h2>Cadastrar Tipo</h2>

<?php
/**
 * @var $form \Zend\Form\Form
 */
$form = $this->form;
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

$this->formElementErrors()
    ->setMessageOpenFormat('<p class="text-danger">')
    ->setMessageCloseString('</p>')
    ->render($form);

$form->prepare();
$form->setAttribute('action', $this->url('tipo/default', array('controller' => 'tipo', 'action' => 'inserir')));


echo $this->form()->openTag($form);

foreach ($form as $element) {
    echo($element->getOpentag());
    if ($element->getAttribute('type') != 'submit') {
        echo($this->formLabel($element));
    }
    echo($this->formInput($element));
    echo($this->formElementErrors($element));
    echo($element->getClosetag());
}

echo $this->form()->closeTag();
?>

