<h2>Editar Operações</h2>

<?php
    /**
     * @var $form \Zend\Form\Form
     */
    $form = $this->form;

    $this->formElementErrors()
        ->setMessageOpenFormat ('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
        ->setMessageCloseString ('</div>')
        ->render ($form);

    $form->setAttribute('action', $this->url('operacoes/default', array('controller' => 'operacoes', 'action' => 'editar', 'id' => $this->id)));

    $form->prepare();

    echo $this->form()->openTag($form);

    echo $this->formCollection($form);

    echo $this->form()->closeTag();
?>