<?php

namespace Operacoes\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperacoesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperacoesRepository extends EntityRepository
{
}
